- name: 'Manage atoms'
  uriPattern: 'atoms(/{@action})'
  defaults:
    '@controller': 'Atom'
    '@package': 'Acme.FusionFlow'
    '@action': 'index'
    '@format': 'html'
  appendExceedingArguments: true
